/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.7.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 12/4/2019
 ***********************************************************************************************/

#ifndef DEEPSTREAM_INTERFACE_H
#define DEEPSTREAM_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/xlogging.h"
#include "azure_c_shared_utility/threadapi.h"

#include "digitaltwin_client_helper.h"
#include "digitaltwin_serializer.h"
#include "parson.h"
#include "../jetson_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum DEEPSTREAM_TELEMETRY_TAG
{
    Deepstream_DEEPSTREAM_STATUS_TELEMETRY,
    Deepstream_DEEPSTREAM_DETECTIONS_TELEMETRY
} DEEPSTREAM_TELEMETRY;

// DigitalTwin interface name from service perspective.
static const char DeepstreamInterfaceId[] = "urn:nvidia:deepstream:1";
static const char DeepstreamInterfaceInstanceName[] = "deepstream";

// Telemetry names for this interface.

static const char DeepstreamInterface_Deepstream_statusTelemetry[] = "deepstream_status";

static const char DeepstreamInterface_Deepstream_detectionsTelemetry[] = "deepstream_detections";

// Property names for this interface.

// Command names for this interface

#define DeepstreamInterface_SetDeepStreamConfigCommand "setDeepStreamConfig"

// Methods
DIGITALTWIN_INTERFACE_CLIENT_HANDLE DeepstreamInterface_Create();

void DeepstreamInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle);

DIGITALTWIN_CLIENT_RESULT DeepstreamInterface_Telemetry_SendAll();

#ifdef __cplusplus
}
#endif

#endif  // DEEPSTREAM_INTERFACE_H
