/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.2.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Thursday, October 10, 2019
 ***********************************************************************************************/

#ifndef DIGITALTWIN_SERIALIZER
#define DIGITALTWIN_SERIALIZER

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "azure_c_shared_utility/xlogging.h"
#include "parson.h"

#include "../jetson_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

bool Deviceinfo_SerializeManufacturerProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeModelProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeSwVersionProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeOsNameProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeTotalStorageProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeTotalMemoryProperty(char * payloadBuffer, int size);

bool Thermalzones_SerializeThermal_zone_0Telemetry(char * payloadBuffer, int size);

bool Thermalzones_SerializeThermal_zone_1Telemetry(char * payloadBuffer, int size);

bool Thermalzones_SerializeThermal_zone_2Telemetry(char * payloadBuffer, int size);

bool Thermalzones_SerializeThermal_zone_3Telemetry(char * payloadBuffer, int size);

bool Thermalzones_SerializeThermal_zone_4Telemetry(char * payloadBuffer, int size);

bool Thermalzones_SerializeThermal_zone_5Telemetry(char * payloadBuffer, int size);

bool Deepstream_SerializeDeepstream_statusTelemetry(char * payloadBuffer, int size);

bool Deepstream_SerializeDeepstream_detectionsTelemetry(char * payloadBuffer, int size);

bool Deepstream_SerializeSetDeepStreamConfigCommandResponse(DEEPSTREAM_SETDEEPSTREAMCONFIG_setDeepStreamConfigResponse* response, char* payloadBuffer, int size);

#ifdef __cplusplus
}
#endif

#endif // DIGITALTWIN_SERIALIZER
